version: '3'

services:
  postgres:
      image: postgres
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - 5432:5432
      networks:
        - market-app-network
      volumes:
        - postgres_data:/var/lib/postgresql/data
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: postgres
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
        KEYCLOAK_IMPORT: /tmp/realm-export.json
      ports:
        - 8080:8080
        - 9990:9990
      depends_on:
        - postgres
        - openldap
      networks:
        - market-app-network
      volumes:
        - ./keycloak/realms/realm-export.json:/tmp/realm-export.json

  openldap:
      image: docker.io/bitnami/openldap:2.6
      environment:
          LDAP_ROOT: dc=trodix,dc=com
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: admin
          LDAP_USERS: user1,user2, user3
          LDAP_PASSWORDS: user1,user2,user3
      ports:
        - 1389:1389
        - 1636:1636
      networks:
        - market-app-network
      volumes:
        - openldap_data:/bitnami/openldap

networks:
  market-app-network:
    driver: bridge
volumes:
  postgres_data:
      driver: local
  openldap_data:
    driver: local
