version: '3'

services:
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - market-app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./keycloak/db/:/docker-entrypoint-initdb.d/

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
    ports:
      - 8080:8080
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --auto-build
    depends_on:
      - postgres
      - openldap
    networks:
      - market-app-network

  openldap:
    image: docker.io/bitnami/openldap:2.6
    environment:
        LDAP_ROOT: dc=trodix,dc=com
        LDAP_ADMIN_USERNAME: admin
        LDAP_ADMIN_PASSWORD: admin
        LDAP_CUSTOM_LDIF_DIR: /ldifs
    ports:
      - 1389:1389
      - 1636:1636
    networks:
      - market-app-network
    volumes:
      - openldap_data:/bitnami/openldap
      - ./ldap/bootstrap:/ldifs

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - 8161:8161
      - 61616:61616

  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      # ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - market-app-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.3
    container_name: kibana
    ports:
      - 5601:5601
      - 9600:9600
    environment:
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      # ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    networks:
      - market-app-network
    volumes:
      - kibana_data:/usr/share/kibana/data


  prometheus:
    image: prom/prometheus
    container_name: 'prometheus'
    network_mode: host
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:9.0.2
    container_name: 'grafana'
    network_mode: host
    env_file:
      - ./monitoring/grafana/config.monitoring
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_RENDERING_SERVER_URL: http://localhost:3001/render
      GF_RENDERING_CALLBACK_URL: http://localhost:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_ALERTING_ENABLED: 'false'
      GF_UNIFIED_ALERTING_ENABLED: 'true'
      GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: 'true'
      GF_FORCE_MIGRATION: 'true'
      GF_SMTP_ENABLED: 'true'
      GF_SMTP_HOST: localhost:1025
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - prometheus
  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    network_mode: host
    environment:
      HTTP_PORT: 3001

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    ports:
      - 5100:9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: monitoring_cadvisor
    ports:
      - 5110:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  maildev:
    image: maildev/maildev
    network_mode: host

networks:
  market-app-network:
    driver: bridge
volumes:
  postgres_data:
      driver: local
  openldap_data:
    driver: local
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
